$env:OLLAMA_NUM_GPU = "999"
$env:OLLAMA_CONTEXT_LENGTH = "32768"
$env:OLLAMA_FLASH_ATTENTION = "1"
$env:OLLAMA_KV_CACHE_TYPE = "q8_0"
$env:OLLAMA_NUM_PARALLEL = "1"
$env:OLLAMA_KEEP_ALIVE = "30m"

ollama serve